services:
  docker-mdns-publisher:
    image: ghcr.io/wschildbach/docker-mdns-publisher:0.10
    build: .
    read_only: true
    restart: on-failure:10
    environment:
      - LOG_LEVEL=INFO # INFO is the default
      - PYTHONUNBUFFERED=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket:ro

# the rest of this file are test/debug services that start, wait a while, then die
  test1:
    image: alpine
    command: "sleep 15"
    profiles: ["debug"]
    depends_on: [docker-mdns-publisher]
    labels: [mdns.publish=test1.local]

  test2:
    image: alpine
    command: "sleep 60"
    profiles: ["debug"]
    depends_on: [docker-mdns-publisher]
    labels: [mdns.publish=test2.local]

  test3:
    image: alpine
    command: "sleep 60"
    profiles: ["debug"]
    depends_on: [docker-mdns-publisher]
    labels: [mdns.publish=test2.local] # publish same label and expect error
